### ISSUE TITLE
[la.container] add matrix market support

### ISSUE THREAD

**Issue by renefritze** [dune-community/dune-xt-la#1]
_From @ftalbrecht on January 20, 2015 19:24_

See http://math.nist.gov/MatrixMarket/. There is also some code available already: http://math.nist.gov/MatrixMarket/mmio-c.html

_Copied from original issue: wwu-numerik/dune-stuff#28_

**Comment by renemilk** [comment]
https://github.com/blattms/dune-mm-amg

**Comment by renemilk** [comment]
_From @ftalbrecht on August 27, 2015 10:31_

Very nice, this should provide a perfect start!

**Comment by tobiasleibner** [comment]
We now have support for reading/writing matrix market files.
