### ISSUE TITLE
Add generic solvers

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt-la#11]
We could add generic solvers which only act on the matrix/vector interface and use this as a fall-back implementation in case no specialization for a backend is found (and also for the sparse matrix in common). As a first step we could copy the [generic solvers from pyMOR](http://pymor.readthedocs.io/en/latest/generated/pymor.algorithms.html#module-pymor.algorithms.genericsolvers), which are copied from scipy.

**Comment by tobiasleibner** [comment]
Moved to dune-xt.
