### ISSUE TITLE
Archive this repository

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-xt-la#118]
Before archiving, we should:
- Delete unused branches, for me everything expect the ``releases/*`` branches can be removed. Other opinions, @dune-community/dune-xt-devs?
- Update Readme to point to the new dune-xt repository

**Comment by ftalbrecht** [comment]
We should check which branches are referenced/used in publications, and keep those. Probably best if each of us lists the ones he still requires.

**Comment by tobiasleibner** [comment]
We decided not to delete the branches before archiving, so we are done here.
