### ISSUE TITLE
dune-istl, superlu and mpi

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt-la#14]
Currently, the `superlu` solver for dune-istl based containers if disabled, if mpi was found (otherwise it is the default). On the other hand it would be useful in serial runs, even if mpi was found. Does anyone remember why it is disabled, @dune-community/dune-xt-la-devs? Must it not be enabled if mpi was found or could it be enabled and just should not be the default?

**Comment by renemilk** [comment]
Was a problem in dune-istl 2.3 IIRC, should be fine now.
