### ISSUE TITLE
(re)add support for FASP solvers

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt-la#16]
This is a reminder that FASP is finally [open source and freely available](http://fasp.sourceforge.net/index.html)!

When I tried it out, their AMG was the fastest iterative solver we had. They seem to support openmp, but not mpi.

**Comment by renefritze** [comment]
Just FYI: there hasn't been a release in over a year and they still have a alpha-level quality disclaimer.

**Comment by tobiasleibner** [comment]
Moved to dune-xt.
