### ISSUE TITLE
[test.la.solver] refactor

### ISSUE THREAD

**Issue by renefritze** [dune-community/dune-xt-la#2]
_From @ftalbrecht on January 20, 2015 19:26_

We should have proper tests of the linear solvers (alos to drop the corresponding test in dune-gdt). Once we have matrix market support #28 we can download some matrices in the `download_external_libraries` step (which is/can be also done on the buildbot) and test all solvers for them.

_Copied from original issue: wwu-numerik/dune-stuff#29_

**Comment by renemilk** [comment]
The reference is ofc to #1

**Comment by tobiasleibner** [comment]
Moved to dune-xt.
