### ISSUE TITLE
Multi-threaded tests

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-xt-la#21]
We should add a multi-threaded test to test thread-safety of the containers. The travis documentation states that there are ~2 cores available, so it should be possible to actually run the test in parallel. I will try to write a simple such test using C++ threads.

**Comment by renemilk** [comment]
We should definitely reconsider out test setup. Currently the main.hxx in xt-common sets the TBB Pool to max_concurrency many workers. I think we should rather set that to 1 for the general case and use the ini file to set this to more. Maybe even oversubscribe the VM for the to be written explicit test.

**Comment by renemilk** [comment]
Would be nice if this included a minimal case to provoke #25

**Comment by tobiasleibner** [comment]
Moved to dune-xt.
