### ISSUE TITLE
[la] add abstraction for eigenvalue computation

### ISSUE THREAD

**Issue by renemilk** [dune-community/dune-xt-la#3]
_From @ftalbrecht on July 23, 2015 6:50_

We have had several occasions where we required the computation of eigenvalues and eigenvectors. I remember @tobiasleibner requiring them for finite volume fluxes in the context of dune-gdt and we require them for the `ESV2007::CutOff` function. Currently this only works when eigen is present. In the long run, it would be nice to have an abstraction for the computation of eigenvalues and eigen vectors, just as we have for the linear solvers

_Copied from original issue: wwu-numerik/dune-stuff#65_

**Comment by renemilk** [comment]
Related: https://dune-project.org/flyspray/index.php?do=details&task_id=1705

**Comment by renemilk** [comment]
Above link is dead. In the meantime Westi did contribute eigenvalue solvers to istl: https://gitlab.dune-project.org/core/dune-istl/tree/master/dune/istl/eigenvalue

**Comment by tobiasleibner** [comment]
Closing this, we now have an abstraction for eigenvalue computation.
