### ISSUE TITLE
valid() of EigenRowMajorSparseMatrix not usable for complex matrices

### ISSUE THREAD

**Issue by renemilk** [dune-community/dune-xt-la#4]
_From @BarbaraV on May 13, 2015 14:28_

This is due to the fact that the EigenMappedDenseVector is only implemented for entries of type double. The matrix-interface forwards the method valid() to the derived implementations, so that one cannot comment out valid() in EigenRowMajorSparseMatrix and use a (slower) method of the interface.

_Copied from original issue: wwu-numerik/dune-stuff#52_

**Comment by renemilk** [comment]
_From @ftalbrecht on May 13, 2015 16:27_

Ok, I thought valid was a virtual method. Since it is a CRTP method this should be fine the way it is, as long as no one calls valid() with complex entries. We will have to implement this in the future, though, as I suspect that you will need this once you start solving the linear system...

**Comment by tobiasleibner** [comment]
Closing this, looks like it was fixed in dune-stuff already (https://github.com/wwu-numerik/dune-stuff/pull/58). Feel free to reopen.
