### ISSUE TITLE
harmonize exceptions

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt-la#5]
I.e., put them in `dune/xt/la/exceptions.hh` into the `Dune::XT::LA::Exceptions` namespace, just like the other modules...

**Comment by tobiasleibner** [comment]
Looks like this can be closed, or are there any exceptions that are not yet moved to ``Dune::XT::LA::Exceptions``?

**Comment by tobiasleibner** [comment]
Closing this for now.
