### ISSUE TITLE
Fix code coverage checks

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-xt-la#73]
For some reasons, gcov takes more memory than available on Travis, see for example
https://travis-ci.org/dune-community/dune-xt-la/jobs/451507996
I added the option ``--ignore-errors gcov`` to ``lcov`` for now which is supposed to ignore all errors stemming from gcov. However, at some point we should investigate why gcov is taking that much memory and fix it properly.

**Comment by renefritze** [comment]
While we moved to Azure for CI and this is no longer a pressing issue, gcov still takes way too much resources imo.

**Comment by tobiasleibner** [comment]
Moved to dune-xt.
